version: "3"
services:
  app:
    container_name: sample-app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo-db
  mongo-db:
    container_name: mongo-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:

