version: "2"
services:
  app:
    container_name: sample-app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo-db
  mongo-db:
    container_name: mongo-db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"