version: "3"
services:
  app:
    container_name: sample-backend
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo-local
    volumes:
      - ~/volumes/dating/uploads/:/uploads/
  mongo-local:
    container_name: mongo-local
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:

